"""user role

Revision ID: 1bf6f42f96a3
Revises: d77a8fb2224f
Create Date: 2022-09-22 09:56:33.504824

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '1bf6f42f96a3'
down_revision = 'd77a8fb2224f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    role_enum = postgresql.ENUM('admin', 'moderator', 'user', name='role', create_type=False)
    role_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('role', role_enum, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
