"""title

Revision ID: d77a8fb2224f
Revises: 25780df44b67
Create Date: 2022-09-17 16:31:51.531647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd77a8fb2224f'
down_revision = '25780df44b67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('titles', sa.Column('name', sa.String(length=250), nullable=False))
    op.create_index(op.f('ix_titles_name'), 'titles', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_titles_name'), table_name='titles')
    op.drop_column('titles', 'name')
    # ### end Alembic commands ###
